package marketmath

import (
	"math"
	rawvolume "socialpredict/handlers/math/marketvolume"
	"socialpredict/handlers/math/outcomes/dbpm"
	"socialpredict/handlers/math/probabilities/wpam"
	"socialpredict/models"
	"sort"
	"time"
)

// GetMarketVolumeWithDust returns the market volume including accumulated dust from selling
// This ensures currency conservation by accounting for dust that remains in the market
func GetMarketVolumeWithDust(bets []models.Bet) int64 {
	baseVolume := GetMarketVolume(bets)
	dustVolume := calculateDustStack(bets)
	return baseVolume + dustVolume
}

// calculateDustStack computes total dust accumulated from all sell transactions
// Uses O(n) single-pass algorithm with chronological processing
func calculateDustStack(bets []models.Bet) int64 {
	if len(bets) == 0 {
		return 0
	}

	// Sort bets chronologically by PlacedAt timestamp
	sortedBets := make([]models.Bet, len(bets))
	copy(sortedBets, bets)
	sort.Slice(sortedBets, func(i, j int) bool {
		return sortedBets[i].PlacedAt.Before(sortedBets[j].PlacedAt)
	})

	totalDust := int64(0)

	// Process bets chronologically, calculating dust for each sell
	for i, bet := range sortedBets {
		if bet.Amount < 0 { // Negative amount indicates a sell transaction
			dust := calculateDustForSellAtIndex(i, sortedBets)
			totalDust += dust
		}
	}

	return totalDust
}

// calculateDustForSell determines dust generated by a specific sell transaction
func calculateDustForSell(sellBet models.Bet, allBets []models.Bet) int64 {
	if sellBet.Amount < 0 {
		sortedBets := make([]models.Bet, len(allBets))
		copy(sortedBets, allBets)
		sort.Slice(sortedBets, func(i, j int) bool {
			return sortedBets[i].PlacedAt.Before(sortedBets[j].PlacedAt)
		})

		for i, bet := range sortedBets {
			if sameBet(bet, sellBet) {
				return calculateDustForSellAtIndex(i, sortedBets)
			}
		}
	}
	return 0
}

func calculateDustForSellAtIndex(sellIndex int, sortedBets []models.Bet) int64 {
	sellBet := sortedBets[sellIndex]
	if sellBet.Amount >= 0 || sellBet.RequestedAmount <= 0 {
		return 0
	}

	preSalePosition := calculateUserPositionBeforeSale(sortedBets[:sellIndex], sellBet.Username)

	sharesOwned := preSalePosition.YesSharesOwned
	if sellBet.Outcome == "NO" {
		sharesOwned = preSalePosition.NoSharesOwned
	}
	if sharesOwned <= 0 || preSalePosition.Value <= 0 {
		return 0
	}

	valuePerShare := preSalePosition.Value / sharesOwned
	if valuePerShare <= 0 {
		return 0
	}

	sharesSold := -sellBet.Amount
	actualCredits := sharesSold * valuePerShare
	dust := sellBet.RequestedAmount - actualCredits
	if dust < 0 {
		return 0
	}
	return dust
}

type sellDustPosition struct {
	Username       string
	YesSharesOwned int64
	NoSharesOwned  int64
	Value          int64
}

func calculateUserPositionBeforeSale(bets []models.Bet, username string) sellDustPosition {
	if len(bets) == 0 {
		return sellDustPosition{Username: username}
	}

	probabilityChanges := wpam.CalculateMarketProbabilitiesWPAM(bets[0].PlacedAt, bets)
	yesShares, noShares := dbpm.DivideUpMarketPoolSharesDBPM(bets, probabilityChanges)
	coursePayouts := dbpm.CalculateCoursePayoutsDBPM(bets, probabilityChanges)
	yesFactor, noFactor := dbpm.CalculateNormalizationFactorsDBPM(yesShares, noShares, coursePayouts)
	scaledPayouts := dbpm.CalculateScaledPayoutsDBPM(bets, coursePayouts, yesFactor, noFactor)
	finalPayouts := dbpm.AdjustPayouts(bets, scaledPayouts)
	positions := dbpm.NetAggregateMarketPositions(dbpm.AggregateUserPayoutsDBPM(bets, finalPayouts))

	valuations := calculateDustValuations(positions, wpam.GetCurrentProbability(probabilityChanges))
	adjustDustValuationsToVolume(valuations, bets, rawvolume.GetMarketVolume(bets))

	for _, position := range positions {
		if position.Username == username {
			return sellDustPosition{
				Username:       username,
				YesSharesOwned: position.YesSharesOwned,
				NoSharesOwned:  position.NoSharesOwned,
				Value:          valuations[username],
			}
		}
	}

	return sellDustPosition{Username: username}
}

func calculateDustValuations(positions []dbpm.DBPMMarketPosition, currentProbability float64) map[string]int64 {
	valuations := make(map[string]int64, len(positions))
	for _, position := range positions {
		var value float64
		if position.YesSharesOwned > 0 {
			value = float64(position.YesSharesOwned) * currentProbability
		} else if position.NoSharesOwned > 0 {
			value = float64(position.NoSharesOwned) * (1 - currentProbability)
		}
		valuations[position.Username] = int64(math.Round(value))
	}
	return valuations
}

func adjustDustValuationsToVolume(valuations map[string]int64, bets []models.Bet, targetVolume int64) {
	holders, sum := buildDustValuationHolders(valuations, bets)
	if len(holders) == 0 {
		return
	}

	delta := targetVolume - sum
	adjustment := int64(1)
	if delta < 0 {
		adjustment = -1
		delta = -delta
	}

	for i := int64(0); i < delta; i++ {
		holder := holders[i%int64(len(holders))]
		valuations[holder.username] += adjustment
	}
}

type dustValuationHolder struct {
	username    string
	value       int64
	earliestBet time.Time
}

func buildDustValuationHolders(valuations map[string]int64, bets []models.Bet) ([]dustValuationHolder, int64) {
	earliestBets := make(map[string]time.Time)
	for _, bet := range bets {
		earliest, ok := earliestBets[bet.Username]
		if !ok || bet.PlacedAt.Before(earliest) {
			earliestBets[bet.Username] = bet.PlacedAt
		}
	}

	holders := make([]dustValuationHolder, 0, len(valuations))
	var sum int64
	for username, value := range valuations {
		if value <= 0 {
			continue
		}
		sum += value
		holders = append(holders, dustValuationHolder{
			username:    username,
			value:       value,
			earliestBet: earliestBets[username],
		})
	}

	sort.Slice(holders, func(i, j int) bool {
		if holders[i].value != holders[j].value {
			return holders[i].value > holders[j].value
		}
		if !holders[i].earliestBet.Equal(holders[j].earliestBet) {
			return holders[i].earliestBet.Before(holders[j].earliestBet)
		}
		return holders[i].username < holders[j].username
	})
	return holders, sum
}

func sameBet(a, b models.Bet) bool {
	if a.ID != 0 || b.ID != 0 {
		return a.ID == b.ID
	}
	return a.Username == b.Username &&
		a.MarketID == b.MarketID &&
		a.Amount == b.Amount &&
		a.RequestedAmount == b.RequestedAmount &&
		a.Outcome == b.Outcome &&
		a.PlacedAt.Equal(b.PlacedAt)
}

// GetMarketDust calculates accumulated dust for a market
// This is a utility function for dust-related calculations
func GetMarketDust(bets []models.Bet) int64 {
	return calculateDustStack(bets)
}
